Develop
shtefannnn/cv pull request #4
Opened 2022-10-24 14:38 UTC by shtefannnn

2022-10-24 15:59 UTC, a1exalexander commented on index.html
> +    <link rel="stylesheet" href="/style.css" />
```suggestion
    <link rel="stylesheet" href="style.css" />
```

2022-10-24 16:06 UTC, a1exalexander requested changes
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/40409129/197572313-69c817c2-7470-4431-b964-54d702d19800.png">

Розміри шрифтів

2022-10-25 09:50 UTC, a1exalexander commented
@shtefannnn Виправ розміри шрифтів!

2022-10-25 19:27 UTC, shtefannnn commented
**-header h1 ничего не менял , вроде бы и так стоит 20рх:** ![image](https://user-images.githubusercontent.com/114100716/197861111-ee5648d1-ad80-4c3e-89ec-5e31fd7d9fea.png)


**-header h2 так же , стоит 14 :** ![image](https://user-images.githubusercontent.com/114100716/197861241-ca31fbd4-f823-426e-9f4e-0b116901424e.png)

**-li так же - 11 :**
![image](https://user-images.githubusercontent.com/114100716/197862874-622f2cb1-b94e-4a74-94ad-40c3d5ed4ee6.png)

Остальные замечания исправил , спасибо за фидбек!

2022-10-26 13:49 UTC, a1exalexander approved these changes

2022-10-26 13:52 UTC, a1exalexander commented
Зараховано! Але виправ краще це ось ці два моменти
![image](https://user-images.githubusercontent.com/40409129/198044502-d102fc68-044e-47ef-bb2b-135df0c2efbd.png)

2022-10-26 13:53 UTC, a1exalexander commented
> **-header h1 ничего не менял , вроде бы и так стоит 20рх:** ![image](https://user-images.githubusercontent.com/114100716/197861111-ee5648d1-ad80-4c3e-89ec-5e31fd7d9fea.png)
> 
> **-header h2 так же , стоит 14 :** ![image](https://user-images.githubusercontent.com/114100716/197861241-ca31fbd4-f823-426e-9f4e-0b116901424e.png)
> 
> **-li так же - 11 :** ![image](https://user-images.githubusercontent.com/114100716/197862874-622f2cb1-b94e-4a74-94ad-40c3d5ed4ee6.png)
> 
> Остальные замечания исправил , спасибо за фидбек!

Та я просто уже все размери шрифтов написал. потому что увидел, что два не совпадают, остальные комом дописал)

2022-10-26 15:04 UTC, shtefannnn commented
цвет поменял , а отступы между тегами <а> я не могу понять как поменять :(

2022-10-26 18:34 UTC, shtefannnn commented
всё сделал , апрувни этот пул реквест что бы я был спокоен )

2022-10-27 13:03 UTC, a1exalexander commented
![image](https://user-images.githubusercontent.com/40409129/198291995-620f2f3b-223d-4ded-84e1-dc94c8210ae2.png)

2022-10-27 13:04 UTC, a1exalexander commented
![image](https://user-images.githubusercontent.com/40409129/198292099-8aa6375b-4a88-4a7b-a2bb-6e14dfc4a2d6.png)

2022-10-27 13:05 UTC, a1exalexander commented
апрувнуто давно! 👍 
просто нажми кнопку мердж, если все доделал

2022-10-27 13:05 UTC, merged

2022-10-27 13:05 UTC, a1exalexander commented
иногда я сам ее нажимаю